### PR TITLE
Make ``ca_certs_locater`` a package - fixes installation issue

### LINKED ISSUE #2: Failed to install on Ubuntu 12.04 precise 32bit
Hi,

after doing::

```
pip install httplib2.ca_certs_locater
```

I get import error if I try to import `ca_certs_locater`::

```
import ca_certs_locater
```

Also I cannot find this file in ve/lib/python2.7/site-packages/

Seems that the installation script doesn's install the `ca_certs_locater.py` file.

### PR DESCRIPTION
**Pull request by kipanshi**
Hi Doug,

  this fixes #2. Can you merge this and upload to Pypi?

### CODE REVIEW

**Comment by kipanshi** [comment]
Hi Doug, will it be possible submit this patch to pypi.python.org?

**Comment by dhellmann** [comment]
Sorry for the delay looking at this. I haven't experienced the installation problem you had, could you give me some more details about what caused that?

**Comment by kipanshi** [comment]
Hi Doug,

it's here https://github.com/dreamhost/httplib2-ca_certs_locater/issues/2

as I started looking at `pbr` documentation, I've found only `packages` options, and it works for me, though `py_modules` don't work, that's why I made `ca_certs_locater` a package, see the diff please

https://github.com/kipanshi/httplib2-ca_certs_locater/commit/d07e6b8cf6b3491b85975c78ce0d597b3e593cdb#diff-380c6a8ebbbce17d55d50ef17d3cf906L25

**Comment by dhellmann** [comment]
I saw the bug. I don't have the same issue installing the package, though, so I'm trying to understand better what is different about your system. I suspect that changing to a package had nothing at all to do with the fix, and that it was actually either the step of installing pbr explicitly or an upgrade to setuptools that fixed this error.

Could you provide more details about the error you saw during installation?

**Comment by dhellmann** [comment]
This fix turns out to be more complex than the required changes. Ryan found a smaller config change in #4 that should also fix the problem.

**Pull request closed without merging**
